# Generated by Django 4.0.6 on 2022-07-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tag_order_customer_order_product_order_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
