# Generated by Django 4.0.6 on 2022-07-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_product_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='product_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
